### ISSUE TITLE
[bug] Remote fails on 2.4/5ghz networks

### ISSUE THREAD

**Issue by ianhyzy** [unfoldedcircle/bug-reports#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Remote Two shows the "wifi not connected symbol" when on a 2.4/5ghz wifi SSID. I have to connect it to a 2.4 only network for it to show the "connected" symbol. 

### How to Reproduce

Connect to a 2.4/5ghz SSID

### Expected behavior

The remote connectes sucesfully on whatever channel it can 

### What part of the system affected by the problem?

Core

### Additional context

Unifi setttings:
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3400872/c449f60a-28ed-46ed-8f80-eed71edae57a)

**Comment by zehnm** [comment]
We are also using the remotes and docks with UniFi access points having both 2.4 and 5 GHz networks for the same SSID and don't face these issues. It's most likely a configuration issue. I'm not a UniFi expert and need to check your settings above.

Other things to check:
- Make sure that your UniFi firmware is up to date.
- Another user had issues with mDNS and it was resolved after rebooting the AP.
- For higher WiFi channels, make sure the country settings in the remote match your region.
  For example don't set the remote to country USA and use it in the EU with high WiFi channels.

**Comment by ianhyzy** [comment]
Firmware is up to date, I rebooted the Dream Machine but still get the same error. I have the same country selected everywhere.

**Comment by zehnm** [comment]
Could you disable `BSS Transition` and test again?

I'm still running an old UniFI controller which doesn't have many of the new advanced options. I'll upgrade it so I can test it too.

**Comment by ianhyzy** [comment]
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3400872/e39c123a-1ec4-41c4-b4f2-b6b528e92c29)
updated on both the shared and _PoS (2.4 only) networks. I got errors when trying to forget a network, and the wificonnection is very weak unless I'm right next to the router (other devices on the network are fine). 

That said, I think it works now. It's on the shared network and I was able to load the configurator. I don't see any Wifi icon at all in the status bar. So that probably fixed it?
