### ISSUE TITLE
Not Charging - useless remote

### ISSUE THREAD

**Issue by wsaal68** [unfoldedcircle/bug-reports#501]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Although the Remote3 is in the dock, it is not loaded.
The web configurator also shows Discharging.

### How to Reproduce

1. Remote3 out the dock
2. and back...

### Expected behavior

Charging

### System version

2.5.6

**Comment by nplawes** [comment]
I have the same issue. Sometimes recoverable by power-cycling the dock and the remote. (2.6.0)

**Comment by wsaal68** [comment]
The remote control is therefore currently USELESS. The battery is running low every day even though the remote control is in the charging cradle. A software update is not possible as the remote control no longer gets above 50%.

**Comment by nplawes** [comment]
I am finding that power cycling the dock does allow it to charge for a short while. Mine is PoE so at least I can do it remotely. Haven't yet spotted any pattern to when it stops. There are frequent disconnect messages in the web configurator which normally require the remote to be picked up to wake it, so maybe that... 

This morning I figured out that putting the remote (albeit upside down) on my wireless phone charger dock it does seem to be charging without any problem (69% and rising). I also notice that there haven't been any web configurator disconnects either. At least, not permanent ones...

While in the dock and remotely power-cycling, the remote was not moved, so it's unlikely to be an issue with bad connections.

I am not sure if I have seen any IR issues with the dock suggesting other faults - I'm still figuring out how to use it after all. I have had some weird stuff happen but it's probably just me. The IR quality/strength does seem somewhat inferior when compared to my harmony though. Early days yet.

**Comment by MinMidMax** [comment]
I’ve experienced the dock charging issue with 2 separate Remote 3 docks several times. One is powered by USB-C and the other is powered by PoE.

Placing the remote in the dock will charge normally. Then at some point, randomly, the remote would stop charging, even with the remote still in the dock. 

Reseating the remote in the dock does not fix this issue. Once the dock is in this state it’s not recoverable until the dock is restarted.

**Comment by wsaal68** [comment]
I can confirm that. It only helps if you disconnect the charging dock from the power supply...

**Comment by smurgier** [comment]
similar behavior here. the remote won't recharge with the dock, or only few percent at a time. Spend all night charging, went from 0 to 14% battery, then drop to 9 then 0 in 5min . With wireless charging, pretty much the same , the remote is very hot to the touch and won't recharge much ( just 2% for the entire day yesterday...
I'm on 2.6.0.

**Comment by zehnm** [comment]
@wsaal68 are you using an USB-C charger or PoE?
In case of USB-C: what model and power rating?

Please contact our support if you have the same issue with different chargers. 
https://support.unfoldedcircle.com/hc/en-us/requests/new

What we have found is that some Docks have a higher variance in measuring the charging current. This is addressed in a soon to be released dock firmware update, since it can trigger the overcurrent protection and charging is switched off. Power-cycling the dock will reset it.

**Comment by smurgier** [comment]
Poe switch

Le mar. 1 juil. 2025, 07:31, Markus Zehnder ***@***.***> a
écrit :

**Comment by mase1981** [comment]
i am having the same issue, remote was on dock all night did not charge at all. moved to wireless charging and the remote will still not charge... i cant get the remote to take charge at all. remote 3.

**Comment by jay7210** [comment]
I also have this issue, 2 docks, PoE powered, will not charge unless power cyle of the dock is carried out. Onlt started having this issue since 2.6.1

**Comment by zehnm** [comment]
New dock firmware is currently being tested with adjusted overcurrent logic. In case such an event is detect, the error will now be displayed on the LCD for better diagnostic.
Code should be pushed tomorrow in the https://github.com/unfoldedcircle/ucd3-firmware repo, with a release soon thereafter.

**Comment by zehnm** [comment]
Dock release v0.7.0 is available in our firmware repository for manual installation. We'll release it in the next hours in the beta OTA channel, followed by the regular update channel about a day later if no new issues pop up.

Manual update:
1. Download binary dock firmware release `UCD3-firmware_r4-v0.7.0.tar.gz` from https://github.com/unfoldedcircle/ucd3-firmware/releases/tag/v0.7.0
2. Extract archive
3. Open the firmware update web-page on the dock: `http://$DOCK_ADDRESS/update/`
   - `$DOCK_ADDRESS` is either the IP address of the dock, or the .local service name.
   - The trailing slash `/` is required.
4. Click `Choose file` and select the file `ucd3-firmware.bin` from the extracted archive.  
   Make sure you choose the correct file and don't select `ucd3-firmware-unsigned.bin`!
5. Click `Upload`
6. In the authentication dialog use `admin` as username and the password of the dock.  
   If no custom password has been set, use the default `0000` pin (4 zeroes).

**Comment by zehnm** [comment]
Dock firmware 0.7.0 has been released in the OTA beta channel and can be updated with the web-configurator.

**Comment by jmillerNeology** [comment]
Tried the manual upload. Received this error:

`Dock closed the connection!`

So... what now? I've tried multiple times.

**Comment by Cantello** [comment]
> `Dock closed the connection!`
> 
> So... what now? I've tried multiple times.

Now that it's been released, try the OTA method from the configurator. I had the same problem with updating and it worked once the remote had reached 25% charge (with much restarting the dock and putting the remote ona Qi charger).

No idea if it solves the original problem, time will tell.

_edit_: after 7 hours, it was still charging without interruption. Seems to work with the same charger.

**Comment by marching-poozer** [comment]
I've had a very similar experience. Updating both the remote and dock to the latest firmware (0.8.1 and 2.6.12) hasn't helped. Here's what I originally posted on the Unfolded Circle Community Forum:

> I’m experiencing an issue with charging but other posts on similar issues have not helped me resolve this.
> 
> I received my Remote 3 and Dock 3 a couple of months ago and initially powered it up and did some basic setup to ensure that everything was working properly. I don’t recall having a specific issue charging the remote on the dock at that time but do recall thinking that it was a bit temperamental.
> 
> Last week I set aside some time to set up the remote properly but, as the dock had been unpowered, the battery on the remote was dead. I placed it on the dock to charge but nothing happened. I left it for 30 minutes - still nothing. However, pressing the power button for a few seconds resulted in:
> 
> - Remote showing low battery screen and “Charging”
> - Dock showing “Charging”
> - Charging stops after a second and dock indicates not charging (bolt with line through it)
>
> 
> I could consistently reproduce this behaviour and discovered that the remote would remain charging for as long as I kept the power button pressed. Again, one second after releasing it charging would stop.
> 
> I repeated this several times for testing/diagnostic purposes and on one occasion charging did continue after I released the power button on the remote. At this point I assumed the issue was gone, left the remote to charge and it eventually booted. Once the remote had charged to ~10% I removed it from the dock and placed it back again. Neither it nor the dock showed any indication of being docked and there was no attempt to charge the remote. The previous technique (holding the power button for 3 seconds) still activated charging intermittently but, again, charging would stop just after releasing the power button.
> 
> Eventually, I gave up and used wireless charging to charge the remote. While the remote was charging I read a post that suggested that some older firmware versions for the dock could/did cause charging issues so I decided to manually update the dock firmware using the ESP Tool however, despite WebSerial being able to see/pair with the dock, I constantly got a “Failed to open serial port” error so eventually gave up . (Other than this and the charging issue, the dock seemed to be functioning as expected - e.g. I could connect to its IP and see its status etc.)
> 
> Once the remote was fully charged, I connected to the web configurator and used it to upgrade the firmware/software on both the dock and the remote (currently running 0.8.0 and 2.6.12 respectively). This did not help.
> 
> I also tried connecting the dock to PoE but the issue remains. I’ve also noticed that the status page for the Dock reports “Invalid Date” for the Time and if I view the Dock on the Remote, its state seems to be in a Connecting/Active/Reconnecting loop.
> 
> To summarise:
> 
> - Placing the Remote on the Dock has no effect - neither the Remote nor the Dock give any indication of a connection and charging is not initiated.
> - Both Remote and Dock are running the latest software/firmware
> - I have tried power-cycling and factory resetting the Dock on multiple occasions
> - I’m using a 65W charger (capable of 3.0A @ 5V) and the cable that came with the Dock
> - Same issue if the Dock is powered with PoE
> - Dock WiFi seems to be in a Connecting/Active/Reconnecting loop
> - Pressing the Remote power button for a few seconds while docked occasionally results in the Dock displaying “Charging” but it stops as soon as I stop pressing the power button
> 
> If it helps, I monitored the power draw of the Dock and it is ~0.76W (~0.15A @ ~5.1V) and does not change when the remote is docked. Also, the voltages between the dock pins are:
> 
> - Pin 1 - Pin 2: ~2.8V
> - Pin 1 - Pin 3: ~5.1V
> - Pin 2 - Pin 3: ~1.2V
> 
> I’m completely out of ideas so would greatly appreciate any help/guidance from anyone. Thanks!

**Comment by zehnm** [comment]
Closing: charging issues are mostly not software related.
 
Please contact support after checking the following:
- The Dock firmware is up to date. Check https://www.unfoldedcircle.com/changelog for latest releases.
- USB-C power supply is capable of min 2.5A at 5V. USB-C PD (Power Delivery) is not supported.
- Dock display does not show "WEAK PWR" (weak power).
  - This means that either the power supply is too weak, or the USB-C cable is too long or of low quality (high voltage drop).
- Issue remains when using a different power supply and USB-C cable.
- Dock and Remote contacts are clean.
- Charging notifications will take up to 10sec to appear on the Dock and the Remote. The notification on the Dock will only be shown for a short time.
- PoE supported standard: 802.3af
 
When contacting support, please include as much information as possible:
- Dock and Remote model (Remote 3 or Remote Two).
- Power supply information and if different power supplies and USB-C cable were already tried out.
- Software versions of Dock and Remote (if devices are still running).
- If wireless charging is working (if wireless charger is available).
- If there are any charging notifications on the Dock screen, for example, CHG OFF (charger switched off, due to over current).
